version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  # Ensure the correct Python version
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Pre-build phase completed. No tests included."

  build:
    commands:
      - echo "Packaging the application..."
      - mkdir -p deploy
      # Copy all files except the deploy/ directory into deploy/
      - rsync -av --exclude='deploy/' ./ deploy/
      
  post_build:
    commands:
      - echo "Build completed successfully."
      - zip -r flask-app.zip deploy/  # Zip the application for deployment
      - echo "Application packaged as flask-app.zip."

artifacts:
  files:
    - flask-app.zip  # Upload the zipped artifact to CodePipeline or Elastic Beanstalk

cache:
  paths:
    - /root/.cache/pip  # Cache pip packages for faster builds
